[build]
target = "crates/game/index.html"
dist = "dist"
public_url = "./"

[serve]
address = "127.0.0.1"
port = 8081
open = true

[watch]
watch = ["crates/game/src", "crates/core/src", "crates/game/index.html"]
ignore = ["dist", "target"]

[clean]
dist = "dist"
cargo = false

[build.wasm]
opt = "z"
bindgen = true
